"""add time_series to routes

Revision ID: e02023c07769
Revises: a4811a9423c3
Create Date: 2026-06-07 15:09:54.328416
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e02023c07769'
down_revision: Union[str, None] = 'a4811a9423c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('time_series', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'time_series')
    # ### end Alembic commands ###
