"""add_training_load_and_daily_training_load

Revision ID: 71a04673b786
Revises: d90ef3147c80
Create Date: 2026-06-09 14:37:22.562529
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71a04673b786'
down_revision: Union[str, None] = 'd90ef3147c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_training_load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('training_load', sa.Float(), nullable=False),
    sa.Column('ctl', sa.Float(), nullable=False),
    sa.Column('atl', sa.Float(), nullable=False),
    sa.Column('tsb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date_training_load')
    )
    op.create_index(op.f('ix_daily_training_load_user_id'), 'daily_training_load', ['user_id'], unique=False)
    op.add_column('activity_stats', sa.Column('training_load', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_stats', 'training_load')
    op.drop_index(op.f('ix_daily_training_load_user_id'), table_name='daily_training_load')
    op.drop_table('daily_training_load')
    # ### end Alembic commands ###
