"""add_gear_service_tracking

Revision ID: 86d73fb7d70c
Revises: cb91b256968a
Create Date: 2026-06-08 16:39:24.981069
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86d73fb7d70c'
down_revision: Union[str, None] = 'cb91b256968a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gear', sa.Column('last_service_date', sa.Date(), nullable=True))
    op.add_column('gear', sa.Column('last_service_distance_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gear', 'last_service_distance_m')
    op.drop_column('gear', 'last_service_date')
    # ### end Alembic commands ###
