"""add zone_6 zone_7 num_zones to user_zones

Revision ID: c3d4e5f6a7b8
Revises: cb91b256968a
Create Date: 2026-08-25 09:15:00.000000
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c3d4e5f6a7b8'
down_revision: str | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_6_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('zone_6_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('zone_7_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('zone_7_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('num_zones', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_zones', schema=None) as batch_op:
        batch_op.drop_column('num_zones')
        batch_op.drop_column('zone_7_max')
        batch_op.drop_column('zone_7_min')
        batch_op.drop_column('zone_6_max')
        batch_op.drop_column('zone_6_min')

    # ### end Alembic commands ###