"""add_routes_table

Revision ID: bbd373f4583f
Revises: e401659b052d
Create Date: 2026-06-11 12:49:08.640589
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bbd373f4583f'
down_revision: Union[str, None] = 'e401659b052d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('waypoints', sa.JSON(), nullable=True),
    sa.Column('route_polyline', sa.Text(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('elevation_loss_m', sa.Float(), nullable=True),
    sa.Column('elevation_profile', sa.JSON(), nullable=True),
    sa.Column('sport_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_user_id'), 'routes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_user_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
