"""add_rest_day_to_training_sessions

Revision ID: d90ef3147c80
Revises: 86d73fb7d70c
Create Date: 2026-06-09 08:26:25.458820
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd90ef3147c80'
down_revision: Union[str, None] = '86d73fb7d70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('rest_day', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'rest_day')
    # ### end Alembic commands ###
